music/urls.py
from django.conf.urls import url
from . import views
app_name='music'

urlpatterns = [
    url(r'^$', views.index,name='index'),

    url(r'^(?P<album_id>[0-9]+)/$',views.detail,name='detail'),

    url(r'^(?P<album_id>[0-9]+)/favorite/$', views.favorite, name='favorite'),

]

web/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^music/', include('music.urls')),

]

music/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class Album(models.Model):
    artist=models.CharField(max_length=250)
    album_title=models.CharField(max_length=500)
    genre=models.CharField(max_length=250)
    album_logo=models.CharField(max_length=500)

    def __str__(self):
        return self.album_title+ ' - ' +self.artist

class Song(models.Model):
    album=models.ForeignKey(Album, on_delete=models.CASCADE)
    file_type=models.CharField(max_length=10)
    song_title=models.CharField(max_length=500)
    is_favorite=models.BooleanField(default=False)


    def __str__(self):
        return self.song_title

music/views.py
from django.shortcuts import render, get_object_or_404
from . models import Album,Song

def index(request):
    all_albums=Album.objects.all()
    return render(request,'music/index.html',{'all_albums' : all_albums})

def detail(request, album_id):
    album=get_object_or_404(Album,pk=album_id)
    return render(request,'music/detail.html',{'album' :album})



def favorite(request, album_id):
    album=get_object_or_404(Album,pk=album_id)
    try:
        selected_song=album.song_set.get(pk=request.POST['song'])
    except(KeyError,Song.DoesNotExist):
        return render(request, 'music/detail.html',{
            'album' :album,
            'error_message':"you didn't select you a valid song",

        })
    else:
        selected_song.is_favorite=True
        selected_song.save()
        return render(request, 'music/detail.html', {'album': album})

music/templates/music/detail.html
<img src="{{ album.album_logo }}">
<h1>{{ album.album_title }}</h1>
<h3>Artist</h3>

{% if error_message %}
        <p><strong>{{error_message}}</strong></p>
{% endif %}

<form action="{% url 'music:favorite' album.id %}" method="post">
    {% csrf_token %}
    {% for song in album.song_set.all %}
        <input type="radio" id="song{{ forloop.counter }}" name="song" value="{{ song.id}}"/>
        <lable for="song{{ forloop.counter }}">
            {{ song.song_title}}
            {% if song.is_favorite %}
                <img src="https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcR5vG38HYdPPwuV7qH3jY7LkLP99nx8nMRF6XAj_2WD3A1COuUKx7esFmk">
                {% endif %}
                </lable><br>
    {% endfor %}
    <input type="submit" value="Favorite">
</form>

music/templates/music/index.html
{% load staticfiles %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<link ref="stylesheet" type="text/css" href="{% static 'music/style.css' %}" />
<link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Satisfy"/>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<nav class="navbar-inverse">
    <div class="container-fluid">

        <div class="navbar-header">

            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>


            </button>
            <a class="navbar-brand" href= "{% url 'music:index'%}">manii </a>

         </div>
        <div class="navbar-collapse">


        </div>
    </div>

</nav>
{% if all_albums %}
<h3>here are all my Albums</h3>
    <ul>
        {% for album in all_albums %}
        <li><a href="{% url 'music:detail' album.id %}">{{ album.album_title }}</a></li>
        {% endfor %}
    </ul>
 {% else %}
    <h1>you don't have any album</h1>
{%endif%}